services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:80"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb_workshop
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw
    ports:
      - "3000:18789"
    environment:
      - OPENAI_API_BASE_URL="http://mercury.cs.fiu.edu:32000/v1"
      - OPENAI_API_KEY="student-secret-2026"
